name: Javascript Linter
run-name: ${{ gitea.actor }} is running eslint
on: [push]

jobs:
  Javascript-Lint:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - name: Install dependencies
        run: |
          npm install eslint

      - name: Run checking
        run: |
          npx eslint app/static/app.js
